export const CATEGORIES = [
  "Women >> Accessories >> Bags (womenswear, accessories, bag)",
  "Women >> Accessories >> Belts (womenswear, accessories, belt)",
  "Women >> Accessories >> Gloves (womenswear, accessories, gloves)",
  "Women >> Accessories >> Hair accessories (womenswear, accessories, hair-accessories)",
  "Women >> Accessories >> Hats and caps (womenswear, accessories, hat)",
  "Women >> Accessories >> Jewellery (womenswear, accessories, jewellery)",
  "Women >> Accessories >> Other (womenswear, accessories, other-accessories)",
  "Women >> Accessories >> Scarves and wraps (womenswear, accessories, scarf-wraps)",
  "Women >> Accessories >> Sunglasses (womenswear, accessories, sunglasses)",
  "Women >> Accessories >> Wallets and cardholders (womenswear, accessories, wallet-purses)",
  "Women >> Accessories >> Watches (womenswear, accessories, watch)",
  "Women >> Bottoms >> Jeans (womenswear, bottoms, jeans)",
  "Women >> Bottoms >> Leggings (womenswear, bottoms, leggings)",
  "Women >> Bottoms >> Other (womenswear, bottoms, other-bottoms)",
  "Women >> Bottoms >> Shorts (womenswear, bottoms, shorts)",
  "Women >> Bottoms >> Skirts (womenswear, bottoms, skirts)",
  "Women >> Bottoms >> Sweatpants (womenswear, bottoms, joggers-tracksuits)",
  "Women >> Bottoms >> Trousers (womenswear, bottoms, trousers)",
  "Women >> Coats and jackets >> Coats (womenswear, coats-jackets, coats)",
  "Women >> Coats and jackets >> Gilets (womenswear, coats-jackets, gilets)",
  "Women >> Coats and jackets >> Jackets (womenswear, coats-jackets, jackets)",
  "Women >> Coats and jackets >> Other (womenswear, coats-jackets, other-coats-jackets)",
  "Women >> Dresses >> Babydoll dresses (womenswear, dresses, babydoll-dresses)",
  "Women >> Dresses >> Bodycon dresses (womenswear, dresses, bodycon-dresses)",
  "Women >> Dresses >> Casual dresses (womenswear, dresses, casual-dresses)",
  "Women >> Dresses >> Dresses (womenswear, dresses, dresses)",
  "Women >> Dresses >> Formal dresses (womenswear, dresses, formal-dresses)",
  "Women >> Dresses >> Going out dresses (womenswear, dresses, going-out-dresses)",
  "Women >> Dresses >> Other (womenswear, dresses, other-dresses)",
  "Women >> Dresses >> Prom dresses (womenswear, dresses, prom-dresses)",
  "Women >> Dresses >> Shift dresses (womenswear, dresses, shift-dresses)",
  "Women >> Dresses >> Shirt dresses (womenswear, dresses, shirt-dresses)",
  "Women >> Dresses >> Summer dresses (womenswear, dresses, summer-dresses)",
  "Women >> Dresses >> Wedding dresses (womenswear, dresses, wedding-dresses)",
  "Women >> Dresses >> Work dresses (womenswear, dresses, work-dresses)",
  "Women >> Dresses >> Wrap dresses (womenswear, dresses, wrap-dresses)",
  "Women >> Fancy dress >> Fancy dress (womenswear, fancy-dress, fancy-dress)",
  "Women >> Footwear >> Ballet shoes (womenswear, footwear, ballet-shoes)",
  "Women >> Footwear >> Boots (womenswear, footwear, boots)",
  "Women >> Footwear >> Flip flops (womenswear, footwear, flipflops)",
  "Women >> Footwear >> Loafers (womenswear, footwear, loafers)",
  "Women >> Footwear >> Other (womenswear, footwear, other-footwear)",
  "Women >> Footwear >> Sandals (womenswear, footwear, sandals)",
  "Women >> Footwear >> Slides (womenswear, footwear, slides)",
  "Women >> Footwear >> Trainers (womenswear, footwear, trainers)",
  "Women >> Jumpsuits and playsuits >> Dungarees (womenswear, jumpsuit-and-playsuit, dungarees-overalls)",
  "Women >> Jumpsuits and playsuits >> Jumpsuits (womenswear, jumpsuit-and-playsuit, jumpsuit)",
  "Women >> Jumpsuits and playsuits >> Other (womenswear, jumpsuit-and-playsuit, other-jumpsuit-and-playsuit)",
  "Women >> Jumpsuits and playsuits >> Playsuits (womenswear, jumpsuit-and-playsuit, playsuit-romper)",
  "Women >> Nightwear >> Pyjamas (womenswear, nightwear, pajamas)",
  "Women >> Nightwear >> Robes (womenswear, nightwear, robes)",
  "Women >> Suits >> Suits (womenswear, suits, suits)",
  "Women >> Suits >> Tailored jackets (womenswear, suits, tailored-jackets)",
  "Women >> Suits >> Tailored trousers (womenswear, suits, tailored-trousers)",
  "Women >> Suits >> Waistcoats (womenswear, suits, waistcoats-vests)",
  "Women >> Swimwear >> Bikini and tankini sets (womenswear, swim-beach-wear, bikinis-and-tankini-sets)",
  "Women >> Swimwear >> Bikini and tankini tops (womenswear, swim-beach-wear, bikini-and-tankini-tops)",
  "Women >> Swimwear >> Cover ups (womenswear, swim-beach-wear, cover-ups)",
  "Women >> Swimwear >> Swimsuits (womenswear, swim-beach-wear, swimsuit-one-piece)",
  "Women >> Tops >> Blouses (womenswear, tops, blouses)",
  "Women >> Tops >> Bodysuits (womenswear, tops, bodysuits)",
  "Women >> Tops >> Cardigans (womenswear, tops, cardigans)",
  "Women >> Tops >> Corsets (womenswear, tops, corsets)",
  "Women >> Tops >> Crop tops (womenswear, tops, crop-top)",
  "Women >> Tops >> Hoodies (womenswear, tops, hoodies)",
  "Women >> Tops >> Jumpers (womenswear, tops, jumpers)",
  "Women >> Tops >> Other (womenswear, tops, other-tops)",
  "Women >> Tops >> Polo shirts (womenswear, tops, polo-shirts)",
  "Women >> Tops >> Shirts (womenswear, tops, shirts)",
  "Women >> Tops >> Sweatshirts (womenswear, tops, sweatshirts)",
  "Women >> Tops >> T-shirts (womenswear, tops, tshirts)",
  "Women >> Tops >> Vests (womenswear, tops, vests-tanks-camis)",
  "Women >> Underwear >> Bras (womenswear, underwear, bras)",
  "Women >> Underwear >> Other (womenswear, underwear, other-underwear)",
  "Women >> Underwear >> Socks (womenswear, underwear, socks)",
  "Women >> Underwear >> Tights (womenswear, underwear, hosiery-tights)",
  "Men >> Tops >> T-shirts (menswear, tops, tshirts)",
  "Men >> Tops >> Shirts (menswear, tops, shirts)",
  "Men >> Tops >> Hoodies (menswear, tops, hoodies)",
  "Men >> Tops >> Sweatshirts (menswear, tops, sweatshirts)",
  "Men >> Bottoms >> Jeans (menswear, bottoms, jeans)",
  "Men >> Bottoms >> Trousers (menswear, bottoms, trousers)",
  "Men >> Bottoms >> Shorts (menswear, bottoms, shorts)",
  "Men >> Coats and jackets >> Jackets (menswear, coats-jackets, jackets)",
  "Men >> Coats and jackets >> Coats (menswear, coats-jackets, coats)",
];

export const CONDITIONS = [
  "Brand new (brand_new)",
  "Like new (used_like_new)",
  "Used - Excellent (used_excellent)",
  "Used - Good (used_good)",
  "Used - Fair (used_fair)",
];

export const COLOURS = [
  "Black (black)",
  "Blue (blue)",
  "Brown (brown)",
  "Burgundy (burgundy)",
  "Cream (cream)",
  "Gold (gold)",
  "Green (green)",
  "Grey (grey)",
  "Khaki (khaki)",
  "Multi (multi)",
  "Navy (navy)",
  "Orange (orange)",
  "Pink (pink)",
  "Purple (purple)",
  "Red (red)",
  "Silver (silver)",
  "Tan (tan)",
  "White (white)",
  "Yellow (yellow)",
];

export const SOURCES = [
  "Custom (custom)",
  "Deadstock (deadstock)",
  "Designer (designer)",
  "Handmade (handmade)",
  "Preloved (preloved)",
  "Repaired (repaired)",
  "Reworked / Upcycled (reworked)",
  "Vintage (vintage)",
];

export const AGES = [
  "00s (y2k)",
  "50s (50s)",
  "60s (60s)",
  "70s (70s)",
  "80s (80s)",
  "90s (90s)",
  "Antique (antique)",
  "Modern (modern)",
];

export const STYLES = [
  "Avant Garde (avant_garde)",
  "Biker (biker)",
  "Boho (boho)",
  "Casual (casual)",
  "Coquette (coquette)",
  "Cosplay (cosplay)",
  "Costume (costume)",
  "Cottage (cottage)",
  "Emo (emo)",
  "Fairy (fairy)",
  "Futuristic (futuristic)",
  "Glam (glam)",
  "Gorpcore (gorpcore)",
  "Goth (goth)",
  "Grunge (grunge)",
  "Indie (indie)",
  "Kidcore (kidcore)",
  "Loungewear (loungewear)",
  "Minimalist (minimalist)",
  "Preppy (preppy)",
  "Punk (punk)",
  "Rave (rave)",
  "Regency (regency)",
  "Retro (retro)",
  "Skater (skater)",
  "Sportswear (sportswear)",
  "Streetwear (streetwear)",
  "Twee (twee)",
  "Utility (techwear)",
  "Western (western)",
  "Whimsygoth (whimsygoth)",
  "Y2K (y2_k)",
];

export const WOMENS_SIZES = [
  "One size",
  "XXS", "XS", "S", "M", "L", "XL", "XXL", "3XL", "4XL",
  "4", "6", "8", "10", "12", "14", "16", "18", "20", "22",
  "Other",
];

export const LOCATION = "Wollongong, Australia";
export const DEFAULT_SOURCE = "Preloved (preloved)";
export const DOMESTIC_SHIPPING = "12";
export const BULK_UPLOAD_SHEET_ID = "1BN5n7orYj4SZydtJa7xs_L-GzT_xUBgh0V39Ss0ouHI";
export const BULK_UPLOAD_TAB = "Use This Template";
